apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/mutable-but-unreadable-fields: '{"spec":{"password":{"valueFrom":{"secretKeyRef":{"key":"password","name":"ts-db-user"}}}}}'
    cnrm.cloud.google.com/project-id: mysamployuhjcacabd12345 #replace this
  finalizers:
  - cnrm.cloud.google.com/finalizer
  - cnrm.cloud.google.com/deletion-defender
  generation: 2
  name: appuser
  namespace: dbtest
spec:
  instanceRef:
    name: mysampleappproj1dbtest
  password:
    value: "stay-Ok-R00t#" 
  resourceID: appuser
