# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    experiments = [module_variable_optional_attrs]
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "4.51.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "4.51.0"
    }
  }
  required_version = "1.2.3"
}
